name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: What would you like to see added or changed?
      placeholder: e.g., Add devcontainer.json for VS Code
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this important? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe how you think this should work
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - Docs only
        - CI/CD
        - Dev Experience
        - Backend
        - Frontend
        - Other

